packages:
  - "packages/*"
  - "apps/*"

allowBuilds:
  '@google/genai': false
  '@parcel/watcher': false
  '@swc/core': false
  '@tailwindcss/oxide': true
  esbuild: true
  lefthook: true
  protobufjs: false
  sharp: true
