import { defineI18n } from "fumadocs-core/i18n";

// The locale set for the marketing landing. Source locale is English; de/es/fr are
// generated by verbatra (see verbatra.config.ts + `pnpm i18n`). Fumadocs owns routing and
// the `[lang]` segment; next-intl owns the message catalog (messages/{locale}.json).
//
// `hideLocale: "default-locale"` keeps English at `/` (no `/en` prefix) and prefixes the
// others (`/de`, `/es`, `/fr`), so every existing inbound link to `/` stays canonical.
// `fallbackLanguage: "en"` means any locale without its own translation falls back to the
// English copy rather than rendering empty — the expected pre-translation state for the
// target catalogs before the verbatra run fills them.
export const i18n = defineI18n({
  defaultLanguage: "en",
  languages: ["en", "de", "es", "fr"],
  hideLocale: "default-locale",
  fallbackLanguage: "en",
});

export type Locale = (typeof i18n.languages)[number];
